server:
  httpPort: 9090
  runMode: debug
  readTimeout: 3600
  writeTimeout: 3600
  # 定义相同的Group之间发送告警通知的时间间隔(s), 组内有告警就一起发出, 没有则单独发出.
  # 第一次产生的告警, 等待10s（为了防止在等待期间,还没有推送告警消息期间这时告警消失了触发了恢复消息）
  groupWait: 10
  # 第二次产生的告警, 等待120s（为了保证告警聚合性相同时间段的告警一起发送）
  groupInterval: 120
  # 告警恢复等待时间，1m（为了防止在告警触发恢复后紧接着再次触发告警条件）
  recoverWait: 1

mysql:
  driverName: mysql
  host: 121.36.93.234:30080
  database: ccloud_test
  username: root
  password: MySQL%5.7
  maxIdleConns: 10
  maxOpenConns: 100
  config: charset=utf8&parseTime=True&loc=Local

clickhouse:
  host: 123.56.214.170:9000
  database: metric
  username: clickhouse_operator
  password: clickhouse_operator_password
  maxIdleConns: 10
  maxOpenConns: 100

redis:
  host: 121.36.93.234
  port: 6321
  pass: Weihu2022@
 # 告警邮箱
mail:
  host: "smtp.163.com"
  pass: "SYDWVDNAXUSMQXMP"
  port: 465
  to: ""
  smtpUser: "Anzj1997@163.com"

jwt:
  # 失效时间
  expire: 18000

zap:
  compress: true
  maxage: 30
  maxbackups: 200
  maxsize: 10
  level: info     #日志级别
  format: console    #输出 json 或者 console
  path: log       #日志输出目录
  showLine: true  #显示行号
  encodeLevel: LowercaseColorLevelEncoder
  logInConsole: true  #输出控制台

# 1）LowercaseLevelEncoder 小写编码器(默认)
# 2）LowercaseColorLevelEncoder 小写编码器带颜色
# 3）CapitalLevelEncoder  大写编码器
# 4） CapitalColorLevelEncoder 大写编码带颜色